apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-2022-std
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: mssql-2022-std
  template:
    metadata:
      labels:
        name: mssql-2022-std
    spec:
      containers:
      - name: mssql-2022-std
        image: mcr.microsoft.com/mssql/rhel/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
      volumeMounts:
     - name: mssql-2022-std
       mountPath: "/var/opt/mssql"
volumeClaimTemplates:
   - metadata:
      name: mssql-2022-std
     spec:
      storageClassName: piraeus-storage
      accessModes:
      - ReadWriteOnce
      resources:
       requests:
        storage: 64Gi
