apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: mcr.microsoft.com/mssql/rhel/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
      volumeMounts:
     - name: mssql-2022-std
       mountPath: "/var/opt/mssql"
volumeClaimTemplates:
   - metadata:
      name: mssql-2022-std
     spec:
      storageClassName: piraeus-storage
      accessModes:
      - ReadWriteOnce
      resources:
       requests:
        storage: 64Gi
