apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Release.Name }}
        image: {{.Values.image}}
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: {{ .Values.secretKey }}
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: {{ .Release.Name }}-volume
          mountPath: "/var/opt/mssql"
      volumes:
      - name: {{ .Release.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-volume

