apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}volume
spec:
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
