apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
spec:
  ports:
  - name: {{ .Release.Name }}
    port: 1433
    targetPort: 1433
  selector:
    name: {{ .Release.Name }}
  type: LoadBalancer
