apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk-raw.fullname" . }}
  labels:
    {{- include "checkmk-raw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "checkmk-raw.selectorLabels" . | nindent 4 }}
